// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_s8gbtochwl0n7hY2M-TqC7YfbfqzTfI',
    appId: '1:834723212018:web:a0c3c0ac728ad48ea57e6b',
    messagingSenderId: '834723212018',
    projectId: 'e-report-27c7e',
    authDomain: 'e-report-27c7e.firebaseapp.com',
    storageBucket: 'e-report-27c7e.appspot.com',
    measurementId: 'G-REPVNRW6BF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz1er9yTJGhcl_D_2YVgHoMiAoPrdmBv8',
    appId: '1:834723212018:android:007b04da7fd1b04ca57e6b',
    messagingSenderId: '834723212018',
    projectId: 'e-report-27c7e',
    storageBucket: 'e-report-27c7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLj4LMEZNNfJ-bzea86_94yswPpGqE3Ng',
    appId: '1:834723212018:ios:df927308098c6684a57e6b',
    messagingSenderId: '834723212018',
    projectId: 'e-report-27c7e',
    storageBucket: 'e-report-27c7e.appspot.com',
    iosBundleId: 'com.example.ereportMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLj4LMEZNNfJ-bzea86_94yswPpGqE3Ng',
    appId: '1:834723212018:ios:7d2b4a92040ead91a57e6b',
    messagingSenderId: '834723212018',
    projectId: 'e-report-27c7e',
    storageBucket: 'e-report-27c7e.appspot.com',
    iosBundleId: 'com.example.ereportMobileApp.RunnerTests',
  );
}
